CHANGELOG.md, Readme.md, imgproxy/Chart.yaml, imgproxy/templates/_helpers.tpl
Sometimes you don't want to have release name as part of pod names.
Example usage:
```yaml
imgproxy:
fullnameOverride: "imgproxy"
```
Resulted pod name: `imgproxy-5c6d97bddd-f4tfn`
=> Add fullnameOverride value to fully control resource naming

CHANGELOG.md, imgproxy/Chart.yaml, imgproxy/templates/deployment.yaml, imgproxy/templates/ingress-health.yaml, imgproxy/values.yaml
This pr adds new version of imgproxy and ability to set deployment annotations.
There are many use cases for this: for example, I want to use special annotations when configuring kube-downscaler rule.
=> Add deployment annotations

imgproxy/templates/deployment.yaml
This should fix issue #13.
Unfortunately, when I tried installing the chart from the master branch (before making this change) the chart failed to install, so this change was tested for version 0.5.9.
=> Fix readinessProbe when using pathPrefix

CHANGELOG.md, imgproxy/Chart.yaml, imgproxy/templates/deployment.yaml
Fixes https://github.com/imgproxy/imgproxy-helm/issues/28
=> Enable IMGPROXY_REPORT_DOWNLOADING_ERRORS to be set to false explicitly

Readme.md, imgproxy/templates/deployment.yaml, imgproxy/templates/serviceaccount.yaml, imgproxy/values.yaml
This PR enables the creation of a service account, useful to leverage eg. AWS IAM role binding (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).
=> Added Kubernetes service account

.github/templates/ISSUE.md, .github/workflows/imgproxy-config-updated.yml
When the imgproxy sends the dispatch event 'imgproxy-updated' to this repository, the local action would publish an issue
and assign it to the gem's maintainers.
We should also add the corresponding action to the `imgproxy/imgproxy` with a write access to this one.
Checked the flow on my own repos and it works:
- [sender](https://github.com/nepalez/attestor/blob/master/.github/workflows/main.yml) (like `imgproxy/imgproxy`)
- [receiver](https://github.com/nepalez/sample_app/blob/master/.github/workflows/main.yml) (like `imgproxy/imgproxy-helm`)
- [the issue](https://github.com/nepalez/sample_app/issues/6)
---
Opened [another PR](https://github.com/imgproxy/imgproxy/pull/634) on the `imgproxy` side
=> Add github action to create an issue about imgproxy changes

imgproxy/templates/deployment.yaml
If the config (secret env) changes, this forces k8s to redeploy the pod.
I've seen this trick in the (old) minio helm chart:
https://github.com/minio/charts/blob/master/minio/templates/deployment.yaml#L57-L58
=> Add checksum/env annotation to deployment

Readme.md, imgproxy/templates/_helpers.tpl, imgproxy/templates/deployment.yaml, imgproxy/values.yaml
This is a follow up on issue #2. The PR allows to serve files from localy attached volume (e.g. NFS shares or RWX).
The PR provides configurations for persistence. When enabled a PVC will be created. Also an existing PVC can be used instead. The PVC will get defined as a volume in the imgproxy deployment and the PV will be mounted at the specified mountPath.
It makes sense to configure IMGPROXY_LOCAL_FILESYSTEM_ROOT separately in the `values.yaml`:
```
features:
security:
allowedSources: "local://"
custom:
IMGPROXY_LOCAL_FILESYSTEM_ROOT: "/images"
```
=> Add PVC and volumeMounts for deployment

CHANGELOG.md, Readme.md, imgproxy/Chart.yaml, imgproxy/README.md, imgproxy/templates/deployment.yaml, imgproxy/values.yaml
It is useful when you need no secret data in your `values.yaml`. For example, in the case of deployment with ArgoCD.
=> Add ability to use existing image pull secrets

CHANGELOG.md, imgproxy/templates/deployment.yaml
https://github.com/imgproxy/imgproxy-helm/issues/65
Deployment.spec.replicas should not exist if HorizontalPodAutoscaler is present otherwise it will cause conflict when using tools like anthos config sync. where deployment.spec.replicas will be constantly changed by both HorizontalPodAutoscaler
and config sync
=> Fix deployment in presence of HPA

imgproxy/templates/ingress-health.yaml
`ingressClassName` field has already added to main ingress resource, but not to ingress-health resource.
=> Add ingressClassName field for ingress-health.yaml

Readme.md, imgproxy/templates/deployment.yaml, imgproxy/values.yaml
Originally the helm chart doesn't support topologySpreadConstraints but they are useful when one runs a big imgproxy deployment and wants to make sure pods are distributed across some constraints evenly. Usually across AZs.
=> Add topologySpreadConstraints support

imgproxy/templates/_versions.tpl
By using the autoscaling/v2 horizontal pod autoscaler version. Helm no longer complains about using a deprecated API version when using Kubernetes 1.23+.
=> Use autoscaling/v2 when available

imgproxy/templates/_helpers.tpl, imgproxy/templates/deployment.yaml, imgproxy/templates/service-account.yaml, imgproxy/values.yaml
Hi,
In my case I needed a way to somehow use the existing service account instead of creating a new one.
This PR introduce these of changes:
1. Service account creation should be explicitly enabled (via `serviceAccount.create`)
2. `serviceAccount.name` allows to explicitly provide name for a serviceAccount, either created or existing
3. [BREAKING] ServiceAccount is not created implicitly when `aws.iamRoleName` or `annotations` is present
Service account settings names in values.yaml are copied from default `helm create` template.
Are you open to these changes?
Though I think explicitness is better, we could found a way to preserve backward compatibility.
=> Granular control over service account creation

Readme.md, imgproxy/README.md, imgproxy/templates/env-secret.yaml, imgproxy/values.yaml
As stated in the [documentation](https://docs.imgproxy.net/configuration?id=log) `gcp` is a valid option for the logging format.
=> Add 'gcp' to allowed logging formats

imgproxy/values.yaml
Although the PDB is enabled, neither minAvailable nor maxUnavailable have been set, which makes the PDB invalid and causes issues. By setting `maxUnavailable: 1` this should be solved.
=> PodDisruptionBudget invalid

imgproxy/templates/_helpers.tpl
Currently, the default CPU limit of "1" cannot be removed, because of the usage of merge here. Using mergeOverwrite will allow us to define "cpu: null" and wipe the CPU limit.
Note: It's worth a mention that in general, CPU limits are an anti-pattern and usually extremely wasteful in production!
=> Use mergeOverwrite to allow overriding limits.cpu with null

Readme.md, imgproxy/README.md, imgproxy/templates/service-monitor.yaml, imgproxy/values.yaml
In our setup we don't use ServiceMonitors. Our auto scraper finds all pods and collects metrics from them if they have the correct annotations. For this setup we need to start the imgproxy metrics server and also expose the metrics endpoint in the Kubernetes service but don't want to start the ServiceMonitor. 
This pull pequest achieves exactly this: It enables ServiceMonitor by default (only when Prometheus is also enabled) to stay downward compatible for all existing deployments but it also allows to disable ServiceMonitor deployment.
=> Make Prometheus ServiceMonitor optional

Readme.md, imgproxy/README.md, imgproxy/templates/deployment.yaml, imgproxy/values.yaml
This pull request introduces an enhancement to the ImgProxy Chart by adding a LifecycleHook, specifically integrating Kubernetes' preStop and preStart lifecycle events.
=> Add LifecycleHook to image proxy chart

imgproxy/README.md
`features.miscellaneous.stripMetadata` was listed twice.
=> Remove duplicate configuration key

imgproxy/templates/deployment.yaml, imgproxy/values.yaml
Add extra Volumes and extra volumeMounts to the deployment
Example:
```
extraVolumeMounts:
- name: selfsigned-volume
mountPath: /usr/local/share/ca-certificates/selsigned.crt
subPath: tls.crt
extraVolumes:
- name: selfsigned-volume
secret:
secretName: selfsigned-ca
```
=> feat: add extraVolumes + extraVolumeMount

.github/templates/ISSUE.md, .github/workflows/imgproxy-config-updated.yml, .github/workflows/release.yml, CHANGELOG.md, Readme.md, imgproxy/README.md, imgproxy/templates/deployment.yaml, imgproxy/values.yaml
This pull request introduces custom settings for podSecurityContext and containerSecurityContext to ensure compatibility with restricted Pod Security Admission levels. 
By adjusting the security context configurationsat the pod and the container level, the application will adhere to the stricter security policies enforced within the Kubernetes cluster.
Currently, the application is unable to run in Kubernetes environments with restricted Pod Security Admission levels due to insufficient security context configurations. This pull request addresses this issue by implementing the necessary adjustments to the security settings, thereby enabling the application to be deployed and run securely in such environments.
When deploying imgproxy in a namespace with pod-security.kubernetes.io/enforce: …
=>  Add custom settings for podSecurityContext and containerSecurityContext instead of global securityContext

Readme.md, imgproxy/values.yaml
Currently, it's not possible to enable ingress without setting `resources.ingress.hosts`. But it's not always necessary to specify a host in the ingress rules. For example, when you use a separate AWS ALB as ingress.
=> Set default resources.ingress.hosts to `[~]`
